### ISSUE TITLE
Deadlines in DB

### ISSUE THREAD

**Issue by Jskobos** [ortonomy/fling-server#7]
Requested features include tracking the reliability of each freelancer, i.e. how often he/she hits or misses deadlines. Tracking this automatically is fairly complicated:

- Where/at what level should deadlines be tracked? By project, freelancer, or separately (e.g. an Assignment relation)
- For ongoing projects with multiple freelancers and deadlines, how should deadlines be tracked?

In the long term, a separate Assignment relation that belongs_to a project is probably the best bet, but this may be too complicated for an MVP. Instead, an option for managers to increment each freelancer's "missed deadlines" field manually may be a simpler choice.

**Comment by ortonomy** [comment]
I'm gonna go ahead and say, let's not even bother with building this for the MVP. I can see the usefulness of the feature, but we need to know more about how it's tracked. This could be different for different projects (as a percentage? as a flag for future use 'misses deadlines: yes / no',  as a graded scale ['always on time','occasionally late','sometimes misses','unreliable with deadlines'] characteristic score. 

Let's put it on the backburner

**Comment by ortonomy** [comment]
Further information from the stakeholder shows that this is unnecessary. They'll use tagging functionality to label a freelancer with any information about deadlines.
