### ISSUE TITLE
Comments functionality

### ISSUE THREAD

**Issue by Jskobos** [ortonomy/fling-server#8]
Role of comments needs to be clarified. At present, they're modeled as simple records (title, text, author_id and timestamps) that can be attached to either a Freelancer (e.g. attached to and displayed on their profile), Project, or Review.

**Comment by ortonomy** [comment]
The stakeholder said this in response to a question

> 1. What can the freelancer do in the system? (For MVP)
> J: Update basic info and availability, see their own profile, being able to make a comment or ask a question would be good. Add new experience.
> M: Don’t think the comment or question thing is a good idea for us, but for an open source thing sure

I think for initial use, this is going to be a 'note' attached to projects, or freelancers, or a freelancer's work on a project. This is going to be dependent on how we design the other parts of the DB.

I think the simple records work as they're going to be arbitrary enough to be mapped to vastly different entities, and they don't need to be linked to each other.

**Comment by Jskobos** [comment]
Agreed. We can just keep the model as is in the schema wiki for now.

**Comment by ortonomy** [comment]
OK, I've updated the schema a little bit so that we have a broadly generic _store_ for ``text_notes``. There's no checking in length of these, so it may be necessary to do validation on the front-end for each type, but the text store will have an intermediate, many-to-many map for each type that they can be attached to. 

There is a built-in enum type to the db which can be extended, but will be used for ``comments``, ``tags``, and ``notes`` for the initial product.

**Enum type:**
````
--  text note types
DROP TYPE IF EXISTS flingapp.text_note_types CASCADE;
CREATE TYPE flingapp.text_note_types AS ENUM(
  'tag',
  'comment',
  'note'
);
COMMENT ON TYPE flingapp.payment_currency IS 'A list of all the possible text note tyeps';
````

**note store:**
````
-- core tag / note / comment store
CREATE TABLE flingapp.text_note(
  id UUID DEFAULT gen_random_uuid(),
  body TEXT NOT NULL,
  type flingapp.text_note_types NOT NULL,
  owner UUID NOT NULL,
  CONSTRAINT text_note_pkey PRIMARY KEY (id),
  CONSTRAINT text_note_owner_fkey FOREIGN KEY (owner)
    REFERENCES flingapp_private.user_account (id)
    ON DELETE RESTRICT
);
-- comment on text notes store
COMMENT ON TABLE flingapp.text_note IS 'A store of all textual notes in the flingapp db';
COMMENT ON COLUMN flingapp.text_note.id IS 'The universally unique ID of a text note';
COMMENT ON COLUMN flingapp.text_note.body IS 'The body text of a text note';
COMMENT ON COLUMN flingapp.text_note.type IS 'The type of the text note e.g. ''tag''';
COMMENT ON COLUMN flingapp.text_note.owner IS 'The universally unique ID of the owner of the text note';
````

**Example map:**
````
-- many-to-many mapping of freelancers to text notes
CREATE TABLE flingapp.freelancer_text_note_map(
  id UUID DEFAULT gen_random_uuid(),
  freelancer UUID NOT NULL,
  text_note UUID NOT NULL,
  CONSTRAINT freelancer_text_note_map_pkey PRIMARY KEY (freelancer, text_note),
  CONSTRAINT freelancer_text_note_map_freelancer_fkey FOREIGN KEY (freelancer)
    REFERENCES flingapp.freelancer (id)
    ON DELETE RESTRICT,
  CONSTRAINT freelancer_text_note_map_text_note_fkey FOREIGN KEY (text_note)
    REFERENCES flingapp.text_note (id)
    ON DELETE CASCADE
);
-- comment on freelancers to text notes
COMMENT ON TABLE flingapp.freelancer_text_note_map IS 'A store of all mappings of text notes to freelancers';
COMMENT ON COLUMN flingapp.freelancer_text_note_map.id IS 'The universally unique ID of a mapping between a text note and a freelancer';
COMMENT ON COLUMN flingapp.freelancer_text_note_map.freelancer IS 'The universally unique ID of a freelancer mapped to a text note';
COMMENT ON COLUMN flingapp.freelancer_text_note_map.text_note IS 'The universally unique ID of a text note mapped to a freelancer';
````
